[2025-01-13T22:38:03.757+0000] {processor.py:161} INFO - Started process (PID=2880) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:38:03.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:38:03.758+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:38:03.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:38:03.922+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:38:03.921+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:38:03.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:38:03.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.182 seconds
[2025-01-13T22:38:34.378+0000] {processor.py:161} INFO - Started process (PID=2936) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:38:34.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:38:34.380+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:38:34.380+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:38:34.568+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:38:34.566+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:38:34.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:38:34.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.207 seconds
[2025-01-13T22:39:04.639+0000] {processor.py:161} INFO - Started process (PID=2997) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:39:04.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:39:04.640+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:39:04.640+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:39:04.814+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:39:04.813+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:39:04.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:39:04.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.191 seconds
[2025-01-13T22:39:34.862+0000] {processor.py:161} INFO - Started process (PID=3054) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:39:34.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:39:34.864+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:39:34.864+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:39:35.029+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:39:35.028+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:39:35.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:39:35.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.181 seconds
[2025-01-13T22:40:05.636+0000] {processor.py:161} INFO - Started process (PID=3113) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:40:05.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:40:05.638+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:40:05.638+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:40:05.820+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:40:05.819+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:40:05.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:40:05.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.199 seconds
[2025-01-13T22:40:36.334+0000] {processor.py:161} INFO - Started process (PID=3172) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:40:36.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:40:36.336+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:40:36.336+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:40:36.501+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:40:36.499+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:40:36.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:40:36.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.182 seconds
[2025-01-13T22:41:07.019+0000] {processor.py:161} INFO - Started process (PID=3231) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:41:07.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:41:07.020+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:41:07.020+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:41:07.182+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:41:07.181+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:41:07.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:41:07.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T22:41:37.675+0000] {processor.py:161} INFO - Started process (PID=3290) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:41:37.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:41:37.677+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:41:37.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:41:37.851+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:41:37.850+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:41:37.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:41:37.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.193 seconds
[2025-01-13T22:42:08.439+0000] {processor.py:161} INFO - Started process (PID=3349) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:42:08.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:42:08.441+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:42:08.441+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:42:08.619+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:42:08.618+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:42:08.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:42:08.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.196 seconds
[2025-01-13T22:42:39.127+0000] {processor.py:161} INFO - Started process (PID=3408) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:42:39.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:42:39.128+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:42:39.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:42:39.298+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:42:39.297+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:42:39.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:42:39.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.187 seconds
[2025-01-13T22:43:09.859+0000] {processor.py:161} INFO - Started process (PID=3467) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:43:09.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:43:09.861+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:43:09.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:43:10.037+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:43:10.036+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:43:10.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:43:10.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.193 seconds
[2025-01-13T22:43:40.495+0000] {processor.py:161} INFO - Started process (PID=3526) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:43:40.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:43:40.497+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:43:40.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:43:40.660+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:43:40.659+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:43:40.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:43:40.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.180 seconds
[2025-01-13T22:44:11.130+0000] {processor.py:161} INFO - Started process (PID=3585) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:44:11.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:44:11.132+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:44:11.132+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:44:11.299+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:44:11.298+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:44:11.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:44:11.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.185 seconds
[2025-01-13T22:44:41.799+0000] {processor.py:161} INFO - Started process (PID=3644) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:44:41.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:44:41.801+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:44:41.800+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:44:41.964+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:44:41.962+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:44:41.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:44:41.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.180 seconds
[2025-01-13T22:45:12.505+0000] {processor.py:161} INFO - Started process (PID=3703) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:45:12.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:45:12.507+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:45:12.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:45:12.681+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:45:12.680+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:45:12.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:45:12.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.191 seconds
[2025-01-13T22:45:43.214+0000] {processor.py:161} INFO - Started process (PID=3762) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:45:43.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:45:43.216+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:45:43.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:45:43.396+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:45:43.395+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:45:43.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:45:43.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.199 seconds
[2025-01-13T22:46:13.866+0000] {processor.py:161} INFO - Started process (PID=3821) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:46:13.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:46:13.868+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:46:13.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:46:14.033+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:46:14.032+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:46:14.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:46:14.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.182 seconds
[2025-01-13T22:46:44.509+0000] {processor.py:161} INFO - Started process (PID=3880) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:46:44.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:46:44.510+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:46:44.510+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:46:44.674+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:46:44.673+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:46:44.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:46:44.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.180 seconds
[2025-01-13T22:47:15.248+0000] {processor.py:161} INFO - Started process (PID=3939) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:47:15.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:47:15.250+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:47:15.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:47:15.424+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:47:15.423+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:47:15.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:47:15.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.192 seconds
[2025-01-13T22:47:45.886+0000] {processor.py:161} INFO - Started process (PID=3998) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:47:45.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:47:45.887+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:47:45.887+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:47:46.086+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:47:46.085+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:47:46.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:47:46.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.215 seconds
[2025-01-13T22:48:16.563+0000] {processor.py:161} INFO - Started process (PID=4057) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:48:16.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:48:16.565+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:48:16.565+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:48:16.732+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:48:16.731+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:48:16.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:48:16.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.184 seconds
[2025-01-13T22:48:47.198+0000] {processor.py:161} INFO - Started process (PID=4116) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:48:47.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:48:47.199+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:48:47.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:48:47.366+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:48:47.365+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:48:47.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:48:47.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.183 seconds
[2025-01-13T22:49:17.984+0000] {processor.py:161} INFO - Started process (PID=4175) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:49:17.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:49:17.985+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:49:17.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:49:18.153+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:49:18.152+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:49:18.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:49:18.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.184 seconds
[2025-01-13T22:49:48.621+0000] {processor.py:161} INFO - Started process (PID=4234) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:49:48.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:49:48.622+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:49:48.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:49:48.806+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:49:48.805+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:49:48.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:49:48.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.201 seconds
[2025-01-13T22:50:19.305+0000] {processor.py:161} INFO - Started process (PID=4293) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:50:19.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:50:19.307+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:50:19.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:50:19.472+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:50:19.471+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:50:19.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:50:19.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.181 seconds
[2025-01-13T22:50:49.948+0000] {processor.py:161} INFO - Started process (PID=4352) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:50:49.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:50:49.949+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:50:49.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:50:50.110+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:50:50.109+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:50:50.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:50:50.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T22:51:20.591+0000] {processor.py:161} INFO - Started process (PID=4411) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:51:20.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:51:20.592+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:51:20.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:51:20.752+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:51:20.751+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:51:20.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:51:20.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.176 seconds
[2025-01-13T22:51:51.212+0000] {processor.py:161} INFO - Started process (PID=4470) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:51:51.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:51:51.213+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:51:51.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:51:51.377+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:51:51.376+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:51:51.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:51:51.391+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.181 seconds
[2025-01-13T22:52:21.900+0000] {processor.py:161} INFO - Started process (PID=4529) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:52:21.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:52:21.902+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:52:21.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:52:22.064+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:52:22.063+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:52:22.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:52:22.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.179 seconds
[2025-01-13T22:52:52.559+0000] {processor.py:161} INFO - Started process (PID=4588) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:52:52.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:52:52.561+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:52:52.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:52:52.720+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:52:52.719+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:52:52.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:52:52.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.176 seconds
[2025-01-13T22:53:23.217+0000] {processor.py:161} INFO - Started process (PID=4647) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:53:23.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:53:23.219+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:53:23.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:53:23.390+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:53:23.389+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:53:23.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:53:23.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.188 seconds
[2025-01-13T22:53:53.921+0000] {processor.py:161} INFO - Started process (PID=4706) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:53:53.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:53:53.922+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:53:53.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:53:54.088+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:53:54.087+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:53:54.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:53:54.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.182 seconds
[2025-01-13T22:54:24.598+0000] {processor.py:161} INFO - Started process (PID=4765) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:54:24.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:54:24.599+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:54:24.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:54:24.761+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:54:24.760+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:54:24.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:54:24.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.180 seconds
[2025-01-13T22:54:55.308+0000] {processor.py:161} INFO - Started process (PID=4830) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:54:55.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:54:55.310+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:54:55.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:54:55.482+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:54:55.481+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:54:55.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:54:55.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.189 seconds
[2025-01-13T22:55:26.027+0000] {processor.py:161} INFO - Started process (PID=4889) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:55:26.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:55:26.028+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:55:26.028+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:55:26.192+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:55:26.191+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:55:26.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:55:26.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.180 seconds
[2025-01-13T22:55:56.717+0000] {processor.py:161} INFO - Started process (PID=4948) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:55:56.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:55:56.719+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:55:56.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:55:56.889+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:55:56.888+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:55:56.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:55:56.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.188 seconds
[2025-01-13T22:56:27.446+0000] {processor.py:161} INFO - Started process (PID=5007) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:56:27.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:56:27.447+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:56:27.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:56:27.611+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:56:27.610+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:56:27.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:56:27.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.181 seconds
[2025-01-13T22:56:58.160+0000] {processor.py:161} INFO - Started process (PID=5066) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:56:58.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:56:58.161+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:56:58.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:56:58.337+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:56:58.336+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:56:58.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:56:58.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.194 seconds
[2025-01-13T22:57:28.804+0000] {processor.py:161} INFO - Started process (PID=5125) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:57:28.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:57:28.806+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:57:28.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:57:28.967+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:57:28.966+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:57:28.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:57:28.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.179 seconds
[2025-01-13T22:57:59.528+0000] {processor.py:161} INFO - Started process (PID=5184) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:57:59.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:57:59.529+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:57:59.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:57:59.697+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:57:59.696+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:57:59.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:57:59.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.184 seconds
[2025-01-13T22:58:30.182+0000] {processor.py:161} INFO - Started process (PID=5243) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:58:30.183+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:58:30.184+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:58:30.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:58:30.349+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:58:30.347+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:58:30.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:58:30.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.183 seconds
[2025-01-13T22:59:00.861+0000] {processor.py:161} INFO - Started process (PID=5302) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:59:00.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:59:00.863+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:59:00.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:59:01.023+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:59:01.022+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:59:01.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:59:01.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.177 seconds
[2025-01-13T22:59:31.467+0000] {processor.py:161} INFO - Started process (PID=5361) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:59:31.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T22:59:31.468+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:59:31.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:59:31.629+0000] {logging_mixin.py:188} INFO - [2025-01-13T22:59:31.628+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T22:59:31.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T22:59:31.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.177 seconds
[2025-01-13T23:00:02.135+0000] {processor.py:161} INFO - Started process (PID=5420) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:00:02.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:00:02.136+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:00:02.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:00:02.297+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:00:02.296+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:00:02.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:00:02.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:00:32.755+0000] {processor.py:161} INFO - Started process (PID=5479) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:00:32.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:00:32.757+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:00:32.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:00:32.919+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:00:32.918+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:00:32.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:00:32.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:01:03.368+0000] {processor.py:161} INFO - Started process (PID=5538) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:01:03.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:01:03.370+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:01:03.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:01:03.535+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:01:03.534+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:01:03.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:01:03.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.182 seconds
[2025-01-13T23:01:34.033+0000] {processor.py:161} INFO - Started process (PID=5597) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:01:34.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:01:34.034+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:01:34.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:01:34.199+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:01:34.198+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:01:34.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:01:34.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.181 seconds
[2025-01-13T23:02:04.722+0000] {processor.py:161} INFO - Started process (PID=5656) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:02:04.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:02:04.723+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:02:04.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:02:04.885+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:02:04.884+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:02:04.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:02:04.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.179 seconds
[2025-01-13T23:02:35.390+0000] {processor.py:161} INFO - Started process (PID=5715) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:02:35.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:02:35.391+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:02:35.391+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:02:35.556+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:02:35.555+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:02:35.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:02:35.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.182 seconds
[2025-01-13T23:03:06.009+0000] {processor.py:161} INFO - Started process (PID=5774) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:03:06.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:03:06.011+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:03:06.011+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:03:06.175+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:03:06.174+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:03:06.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:03:06.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.180 seconds
[2025-01-13T23:03:36.611+0000] {processor.py:161} INFO - Started process (PID=5833) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:03:36.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:03:36.612+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:03:36.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:03:36.790+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:03:36.789+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:03:36.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:03:36.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.196 seconds
[2025-01-13T23:04:07.262+0000] {processor.py:161} INFO - Started process (PID=5892) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:04:07.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:04:07.264+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:04:07.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:04:07.426+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:04:07.425+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:04:07.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:04:07.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:04:37.969+0000] {processor.py:161} INFO - Started process (PID=5951) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:04:37.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:04:37.970+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:04:37.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:04:38.131+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:04:38.130+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:04:38.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:04:38.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:05:08.641+0000] {processor.py:161} INFO - Started process (PID=6010) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:05:08.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:05:08.643+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:05:08.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:05:08.803+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:05:08.802+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:05:08.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:05:08.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.177 seconds
[2025-01-13T23:05:39.408+0000] {processor.py:161} INFO - Started process (PID=6069) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:05:39.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:05:39.409+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:05:39.409+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:05:39.581+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:05:39.580+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:05:39.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:05:39.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.189 seconds
[2025-01-13T23:06:10.165+0000] {processor.py:161} INFO - Started process (PID=6128) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:06:10.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:06:10.167+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:06:10.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:06:10.328+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:06:10.326+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:06:10.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:06:10.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.177 seconds
[2025-01-13T23:06:40.784+0000] {processor.py:161} INFO - Started process (PID=6187) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:06:40.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:06:40.785+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:06:40.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:06:40.950+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:06:40.949+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:06:40.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:06:40.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.182 seconds
[2025-01-13T23:07:11.423+0000] {processor.py:161} INFO - Started process (PID=6246) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:07:11.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:07:11.424+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:07:11.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:07:11.587+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:07:11.586+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:07:11.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:07:11.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:07:42.147+0000] {processor.py:161} INFO - Started process (PID=6305) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:07:42.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:07:42.148+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:07:42.148+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:07:42.406+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:07:42.405+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:07:42.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:07:42.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.273 seconds
[2025-01-13T23:08:12.871+0000] {processor.py:161} INFO - Started process (PID=6364) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:08:12.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:08:12.872+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:08:12.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:08:13.164+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:08:13.163+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:08:13.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:08:13.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.308 seconds
[2025-01-13T23:08:43.542+0000] {processor.py:161} INFO - Started process (PID=6423) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:08:43.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:08:43.543+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:08:43.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:08:43.828+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:08:43.828+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:08:43.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:08:43.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.301 seconds
[2025-01-13T23:09:14.279+0000] {processor.py:161} INFO - Started process (PID=6482) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:09:14.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:09:14.281+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:09:14.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:09:14.532+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:09:14.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:09:14.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:09:14.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.267 seconds
[2025-01-13T23:09:44.979+0000] {processor.py:161} INFO - Started process (PID=6541) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:09:44.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:09:44.981+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:09:44.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:09:45.241+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:09:45.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:09:45.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:09:45.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.276 seconds
[2025-01-13T23:10:15.702+0000] {processor.py:161} INFO - Started process (PID=6600) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:10:15.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:10:15.703+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:10:15.703+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:10:15.960+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:10:15.959+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:10:15.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:10:15.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.272 seconds
[2025-01-13T23:10:46.486+0000] {processor.py:161} INFO - Started process (PID=6659) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:10:46.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:10:46.487+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:10:46.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:10:46.740+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:10:46.740+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:10:46.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:10:46.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.269 seconds
[2025-01-13T23:11:17.533+0000] {processor.py:161} INFO - Started process (PID=6718) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:11:17.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:11:17.535+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:11:17.535+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:11:17.799+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:11:17.798+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:11:17.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:11:17.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.279 seconds
[2025-01-13T23:11:48.753+0000] {processor.py:161} INFO - Started process (PID=6780) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:11:48.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:11:48.754+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:11:48.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:11:49.030+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:11:49.029+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:11:49.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:11:49.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.290 seconds
[2025-01-13T23:12:19.132+0000] {processor.py:161} INFO - Started process (PID=6840) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:12:19.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:12:19.133+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:12:19.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:12:19.404+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:12:19.403+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:12:19.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:12:19.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.286 seconds
[2025-01-13T23:12:49.920+0000] {processor.py:161} INFO - Started process (PID=6898) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:12:49.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:12:49.921+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:12:49.921+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:12:50.211+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:12:50.211+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:12:50.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:12:50.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.305 seconds
[2025-01-13T23:13:20.248+0000] {processor.py:161} INFO - Started process (PID=6957) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:13:20.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:13:20.249+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:13:20.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:13:20.519+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:13:20.518+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:13:20.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:13:20.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.287 seconds
[2025-01-13T23:13:51.134+0000] {processor.py:161} INFO - Started process (PID=7014) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:13:51.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:13:51.136+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:13:51.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:13:51.398+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:13:51.398+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:13:51.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:13:51.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.280 seconds
[2025-01-13T23:14:22.235+0000] {processor.py:161} INFO - Started process (PID=7073) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:14:22.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:14:22.240+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:14:22.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:14:22.525+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:14:22.524+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:14:22.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:14:22.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.305 seconds
[2025-01-13T23:14:53.447+0000] {processor.py:161} INFO - Started process (PID=7132) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:14:53.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:14:53.448+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:14:53.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:14:53.726+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:14:53.725+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:14:53.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:14:53.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.294 seconds
[2025-01-13T23:15:24.596+0000] {processor.py:161} INFO - Started process (PID=7191) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:15:24.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:15:24.599+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:15:24.598+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:15:24.894+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:15:24.893+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:15:24.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:15:24.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.312 seconds
[2025-01-13T23:15:55.879+0000] {processor.py:161} INFO - Started process (PID=7256) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:15:55.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:15:55.881+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:15:55.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:15:56.144+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:15:56.143+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:15:56.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:15:56.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.279 seconds
[2025-01-13T23:16:27.099+0000] {processor.py:161} INFO - Started process (PID=7315) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:16:27.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:16:27.100+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:16:27.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:16:27.372+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:16:27.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:16:27.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:16:27.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.289 seconds
[2025-01-13T23:16:58.360+0000] {processor.py:161} INFO - Started process (PID=7374) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:16:58.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:16:58.361+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:16:58.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:16:58.640+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:16:58.639+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:16:58.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:16:58.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.295 seconds
[2025-01-13T23:17:29.596+0000] {processor.py:161} INFO - Started process (PID=7433) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:17:29.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:17:29.597+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:17:29.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:17:29.879+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:17:29.878+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:17:29.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:17:29.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.298 seconds
[2025-01-13T23:18:00.816+0000] {processor.py:161} INFO - Started process (PID=7492) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:18:00.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:18:00.817+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:18:00.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:18:01.111+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:18:01.110+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:18:01.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:18:01.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.311 seconds
[2025-01-13T23:18:32.084+0000] {processor.py:161} INFO - Started process (PID=7551) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:18:32.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:18:32.086+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:18:32.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:18:32.386+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:18:32.385+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:18:32.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:18:32.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.316 seconds
[2025-01-13T23:19:03.179+0000] {processor.py:161} INFO - Started process (PID=7610) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:19:03.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:19:03.181+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:19:03.180+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:19:03.457+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:19:03.456+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:19:03.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:19:03.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.293 seconds
[2025-01-13T23:19:34.376+0000] {processor.py:161} INFO - Started process (PID=7669) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:19:34.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:19:34.377+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:19:34.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:19:34.655+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:19:34.655+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:19:34.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:19:34.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.294 seconds
[2025-01-13T23:20:05.498+0000] {processor.py:161} INFO - Started process (PID=7728) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:20:05.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:20:05.500+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:20:05.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:20:05.770+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:20:05.769+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:20:05.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:20:05.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.285 seconds
[2025-01-13T23:20:36.656+0000] {processor.py:161} INFO - Started process (PID=7787) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:20:36.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:20:36.657+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:20:36.657+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:20:36.917+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:20:36.916+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:20:36.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:20:36.931+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.277 seconds
[2025-01-13T23:21:07.839+0000] {processor.py:161} INFO - Started process (PID=7846) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:21:07.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:21:07.841+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:21:07.841+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:21:08.107+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:21:08.106+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:21:08.107+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:21:08.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.281 seconds
[2025-01-13T23:21:38.145+0000] {processor.py:161} INFO - Started process (PID=7905) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:21:38.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:21:38.147+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:21:38.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:21:38.402+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:21:38.401+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:21:38.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:21:38.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.272 seconds
[2025-01-13T23:22:08.528+0000] {processor.py:161} INFO - Started process (PID=7964) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:22:08.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:22:08.530+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:22:08.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:22:08.797+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:22:08.797+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:22:08.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:22:08.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.283 seconds
[2025-01-13T23:22:38.899+0000] {processor.py:161} INFO - Started process (PID=8023) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:22:38.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:22:38.901+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:22:38.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:22:39.150+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:22:39.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:22:39.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:22:39.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.264 seconds
[2025-01-13T23:23:09.239+0000] {processor.py:161} INFO - Started process (PID=8082) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:23:09.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:23:09.241+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:23:09.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:23:09.507+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:23:09.507+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:23:09.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:23:09.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.282 seconds
[2025-01-13T23:23:39.543+0000] {processor.py:161} INFO - Started process (PID=8141) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:23:39.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:23:39.545+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:23:39.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:23:39.827+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:23:39.827+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:23:39.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:23:39.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.298 seconds
[2025-01-13T23:24:10.024+0000] {processor.py:161} INFO - Started process (PID=8200) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:24:10.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:24:10.026+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:24:10.026+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:24:10.288+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:24:10.287+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:24:10.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:24:10.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.279 seconds
[2025-01-13T23:24:41.250+0000] {processor.py:161} INFO - Started process (PID=8261) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:24:41.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:24:41.252+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:24:41.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:24:41.505+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:24:41.505+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:24:41.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:24:41.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.272 seconds
[2025-01-13T23:25:12.465+0000] {processor.py:161} INFO - Started process (PID=8320) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:25:12.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:25:12.467+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:25:12.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:25:12.752+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:25:12.752+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:25:12.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:25:12.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.301 seconds
[2025-01-13T23:25:43.572+0000] {processor.py:161} INFO - Started process (PID=8379) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:25:43.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:25:43.574+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:25:43.574+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:25:43.829+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:25:43.828+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:25:43.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:25:43.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.271 seconds
[2025-01-13T23:26:14.711+0000] {processor.py:161} INFO - Started process (PID=8438) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:26:14.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:26:14.712+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:26:14.712+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:26:15.000+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:26:14.999+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:26:15.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:26:15.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.304 seconds
[2025-01-13T23:26:45.926+0000] {processor.py:161} INFO - Started process (PID=8497) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:26:45.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:26:45.927+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:26:45.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:26:46.191+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:26:46.190+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:26:46.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:26:46.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.279 seconds
[2025-01-13T23:27:17.037+0000] {processor.py:161} INFO - Started process (PID=8556) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:27:17.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:27:17.040+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:27:17.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:27:17.297+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:27:17.296+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:27:17.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:27:17.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.274 seconds
[2025-01-13T23:27:47.855+0000] {processor.py:161} INFO - Started process (PID=8615) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:27:47.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:27:47.857+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:27:47.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:27:48.142+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:27:48.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:27:48.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:27:48.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.302 seconds
[2025-01-13T23:28:19.069+0000] {processor.py:161} INFO - Started process (PID=8674) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:28:19.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:28:19.070+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:28:19.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:28:19.350+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:28:19.349+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:28:19.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:28:19.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.296 seconds
[2025-01-13T23:28:50.162+0000] {processor.py:161} INFO - Started process (PID=8733) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:28:50.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:28:50.163+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:28:50.163+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:28:50.426+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:28:50.426+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:28:50.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:28:50.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.279 seconds
[2025-01-13T23:29:21.315+0000] {processor.py:161} INFO - Started process (PID=8793) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:29:21.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:29:21.316+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:29:21.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:29:21.602+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:29:21.601+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:29:21.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:29:21.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.302 seconds
[2025-01-13T23:29:52.520+0000] {processor.py:161} INFO - Started process (PID=8852) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:29:52.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:29:52.522+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:29:52.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:29:52.785+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:29:52.784+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:29:52.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:29:52.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.279 seconds
[2025-01-13T23:30:23.723+0000] {processor.py:161} INFO - Started process (PID=8911) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:30:23.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:30:23.725+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:30:23.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:30:24.004+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:30:24.003+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:30:24.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:30:24.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.295 seconds
[2025-01-13T23:30:54.849+0000] {processor.py:161} INFO - Started process (PID=8970) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:30:54.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:30:54.850+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:30:54.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:30:55.107+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:30:55.106+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:30:55.107+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:30:55.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.272 seconds
[2025-01-13T23:31:25.959+0000] {processor.py:161} INFO - Started process (PID=9029) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:31:25.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:31:25.962+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:31:25.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:31:26.236+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:31:26.236+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:31:26.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:31:26.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.291 seconds
[2025-01-13T23:31:56.331+0000] {processor.py:161} INFO - Started process (PID=9088) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:31:56.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:31:56.333+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:31:56.332+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:31:56.604+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:31:56.603+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:31:56.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:31:56.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.287 seconds
[2025-01-13T23:32:26.641+0000] {processor.py:161} INFO - Started process (PID=9153) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:32:26.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:32:26.642+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:32:26.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:32:26.886+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:32:26.885+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:32:26.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:32:26.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.259 seconds
[2025-01-13T23:32:56.919+0000] {processor.py:161} INFO - Started process (PID=9212) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:32:56.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:32:56.921+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:32:56.921+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:32:57.168+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:32:57.167+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:32:57.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:32:57.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.262 seconds
[2025-01-13T23:33:27.590+0000] {processor.py:161} INFO - Started process (PID=9271) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:33:27.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:33:27.591+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:33:27.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:33:27.847+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:33:27.847+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:33:27.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:33:27.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.271 seconds
[2025-01-13T23:33:58.104+0000] {processor.py:161} INFO - Started process (PID=9330) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:33:58.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:33:58.106+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:33:58.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:33:58.420+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:33:58.420+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:33:58.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:33:58.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.330 seconds
[2025-01-13T23:34:28.494+0000] {processor.py:161} INFO - Started process (PID=9389) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:34:28.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:34:28.495+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:34:28.495+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:34:28.760+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:34:28.759+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:34:28.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:34:28.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.281 seconds
[2025-01-13T23:34:59.521+0000] {processor.py:161} INFO - Started process (PID=9448) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:34:59.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:34:59.523+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:34:59.523+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:34:59.683+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:34:59.682+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:34:59.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:34:59.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:35:30.199+0000] {processor.py:161} INFO - Started process (PID=9508) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:35:30.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:35:30.200+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:35:30.200+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:35:30.367+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:35:30.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:35:30.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:35:30.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.185 seconds
[2025-01-13T23:36:00.911+0000] {processor.py:161} INFO - Started process (PID=9567) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:36:00.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:36:00.912+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:36:00.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:36:01.078+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:36:01.077+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:36:01.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:36:01.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.183 seconds
[2025-01-13T23:36:31.607+0000] {processor.py:161} INFO - Started process (PID=9626) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:36:31.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:36:31.609+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:36:31.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:36:31.775+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:36:31.774+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:36:31.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:36:31.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.183 seconds
[2025-01-13T23:37:02.206+0000] {processor.py:161} INFO - Started process (PID=9685) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:37:02.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:37:02.207+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:37:02.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:37:02.368+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:37:02.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:37:02.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:37:02.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:37:32.792+0000] {processor.py:161} INFO - Started process (PID=9744) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:37:32.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:37:32.793+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:37:32.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:37:32.953+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:37:32.952+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:37:32.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:37:32.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.176 seconds
[2025-01-13T23:38:03.358+0000] {processor.py:161} INFO - Started process (PID=9803) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:38:03.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:38:03.359+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:38:03.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:38:03.540+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:38:03.539+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:38:03.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:38:03.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.198 seconds
[2025-01-13T23:38:33.980+0000] {processor.py:161} INFO - Started process (PID=9862) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:38:33.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:38:33.982+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:38:33.982+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:38:34.143+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:38:34.142+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:38:34.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:38:34.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:39:04.597+0000] {processor.py:161} INFO - Started process (PID=9921) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:39:04.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:39:04.599+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:39:04.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:39:04.761+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:39:04.760+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:39:04.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:39:04.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.179 seconds
[2025-01-13T23:39:35.346+0000] {processor.py:161} INFO - Started process (PID=9980) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:39:35.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:39:35.347+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:39:35.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:39:35.509+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:39:35.507+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:39:35.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:39:35.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.178 seconds
[2025-01-13T23:40:05.989+0000] {processor.py:161} INFO - Started process (PID=10039) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:40:05.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:40:05.990+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:40:05.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:40:06.152+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:40:06.151+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:40:06.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:40:06.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.179 seconds
[2025-01-13T23:40:36.634+0000] {processor.py:161} INFO - Started process (PID=10098) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:40:36.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:40:36.636+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:40:36.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:40:36.799+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:40:36.798+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:40:36.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:40:36.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.181 seconds
[2025-01-13T23:41:07.288+0000] {processor.py:161} INFO - Started process (PID=10157) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:41:07.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:41:07.290+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:41:07.289+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:41:07.447+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:41:07.446+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:41:07.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:41:07.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.175 seconds
[2025-01-13T23:41:37.876+0000] {processor.py:161} INFO - Started process (PID=10216) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:41:37.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:41:37.877+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:41:37.877+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:41:38.062+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:41:38.061+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:41:38.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:41:38.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.201 seconds
[2025-01-13T23:57:35.582+0000] {processor.py:161} INFO - Started process (PID=10275) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:57:35.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:57:35.584+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:57:35.584+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:57:35.816+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:57:35.815+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:57:35.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:57:35.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.254 seconds
[2025-01-13T23:58:05.877+0000] {processor.py:161} INFO - Started process (PID=10332) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:58:05.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:58:05.878+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:58:05.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:58:06.069+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:58:06.068+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:58:06.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:58:06.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.209 seconds
[2025-01-13T23:58:37.029+0000] {processor.py:161} INFO - Started process (PID=10391) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:58:37.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:58:37.031+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:58:37.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:58:37.210+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:58:37.209+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:58:37.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:58:37.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.198 seconds
[2025-01-13T23:59:07.914+0000] {processor.py:161} INFO - Started process (PID=10450) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:59:07.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:59:07.916+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:59:07.916+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:59:08.093+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:59:08.092+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:59:08.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:59:08.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.196 seconds
[2025-01-13T23:59:38.831+0000] {processor.py:161} INFO - Started process (PID=10509) to work on /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:59:38.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_pipeline_dag copy.py for tasks to queue
[2025-01-13T23:59:38.832+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:59:38.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:59:39.015+0000] {logging_mixin.py:188} INFO - [2025-01-13T23:59:39.014+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_pipeline_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_pipeline_dag copy.py", line 8, in <module>
    from sklearn.preprocessing import MinMaxScaler
ModuleNotFoundError: No module named 'sklearn'
[2025-01-13T23:59:39.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_pipeline_dag copy.py
[2025-01-13T23:59:39.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_pipeline_dag copy.py took 0.200 seconds
